/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as StoreRouteImport } from './routes/store'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StoreIndexRouteImport } from './routes/store/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as StoreSearchRouteImport } from './routes/store/search'
import { Route as StorePaymentRouteImport } from './routes/store/payment'
import { Route as StoreCheckoutRouteImport } from './routes/store/checkout'
import { Route as StoreCategoriesRouteImport } from './routes/store/categories'
import { Route as StoreCartRouteImport } from './routes/store/cart'
import { Route as StoreAccountRouteImport } from './routes/store/account'
import { Route as LojaSlugOuIdRouteImport } from './routes/loja.$slugOuId'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminStockRouteImport } from './routes/admin/stock'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminSectorsRouteImport } from './routes/admin/sectors'
import { Route as AdminReportsPreviewRouteImport } from './routes/admin/reports-preview'
import { Route as AdminReportsDashboardRouteImport } from './routes/admin/reports-dashboard'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminProductsRouteImport } from './routes/admin/products'
import { Route as AdminPrintersRouteImport } from './routes/admin/printers'
import { Route as AdminPrintEnvironmentsRouteImport } from './routes/admin/print-environments'
import { Route as AdminPdvRouteImport } from './routes/admin/pdv'
import { Route as AdminOrdersRouteImport } from './routes/admin/orders'
import { Route as AdminFinancialRouteImport } from './routes/admin/financial'
import { Route as AdminDeliveryRouteImport } from './routes/admin/delivery'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminCustomersRouteImport } from './routes/admin/customers'
import { Route as AdminCouponsRouteImport } from './routes/admin/coupons'
import { Route as AdminCategoriesRouteImport } from './routes/admin/categories'
import { Route as AdminStockIndexRouteImport } from './routes/admin/stock/index'
import { Route as AdminFinancialIndexRouteImport } from './routes/admin/financial/index'
import { Route as StoreProductProductIdRouteImport } from './routes/store/product.$productId'
import { Route as StoreOrderOrderIdRouteImport } from './routes/store/order.$orderId'
import { Route as AdminStockTransfersRouteImport } from './routes/admin/stock/transfers'
import { Route as AdminStockHistoryRouteImport } from './routes/admin/stock/history'
import { Route as AdminStockExtractRouteImport } from './routes/admin/stock/extract'
import { Route as AdminStockExitsRouteImport } from './routes/admin/stock/exits'
import { Route as AdminStockEntriesRouteImport } from './routes/admin/stock/entries'
import { Route as AdminStockBalanceteRouteImport } from './routes/admin/stock/balancete'
import { Route as AdminStockBalanceRouteImport } from './routes/admin/stock/balance'
import { Route as AdminStockAdjustmentsRouteImport } from './routes/admin/stock/adjustments'
import { Route as AdminFinancialSettingsRouteImport } from './routes/admin/financial/settings'
import { Route as AdminFinancialSessionsRouteImport } from './routes/admin/financial/sessions'
import { Route as AdminFinancialReceivablesRouteImport } from './routes/admin/financial/receivables'
import { Route as AdminFinancialPayablesRouteImport } from './routes/admin/financial/payables'
import { Route as AdminFinancialMovementsRouteImport } from './routes/admin/financial/movements'
import { Route as AdminFinancialHistoryRouteImport } from './routes/admin/financial/history'
import { Route as AdminFinancialDreRouteImport } from './routes/admin/financial/dre'
import { Route as AdminFinancialCashflowRouteImport } from './routes/admin/financial/cashflow'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreIndexRoute = StoreIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StoreRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const StoreSearchRoute = StoreSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => StoreRoute,
} as any)
const StorePaymentRoute = StorePaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => StoreRoute,
} as any)
const StoreCheckoutRoute = StoreCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => StoreRoute,
} as any)
const StoreCategoriesRoute = StoreCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => StoreRoute,
} as any)
const StoreCartRoute = StoreCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => StoreRoute,
} as any)
const StoreAccountRoute = StoreAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => StoreRoute,
} as any)
const LojaSlugOuIdRoute = LojaSlugOuIdRouteImport.update({
  id: '/loja/$slugOuId',
  path: '/loja/$slugOuId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStockRoute = AdminStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSectorsRoute = AdminSectorsRouteImport.update({
  id: '/sectors',
  path: '/sectors',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsPreviewRoute = AdminReportsPreviewRouteImport.update({
  id: '/reports-preview',
  path: '/reports-preview',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsDashboardRoute = AdminReportsDashboardRouteImport.update({
  id: '/reports-dashboard',
  path: '/reports-dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPrintersRoute = AdminPrintersRouteImport.update({
  id: '/printers',
  path: '/printers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPrintEnvironmentsRoute = AdminPrintEnvironmentsRouteImport.update({
  id: '/print-environments',
  path: '/print-environments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPdvRoute = AdminPdvRouteImport.update({
  id: '/pdv',
  path: '/pdv',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinancialRoute = AdminFinancialRouteImport.update({
  id: '/financial',
  path: '/financial',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDeliveryRoute = AdminDeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCouponsRoute = AdminCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStockIndexRoute = AdminStockIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminStockRoute,
} as any)
const AdminFinancialIndexRoute = AdminFinancialIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminFinancialRoute,
} as any)
const StoreProductProductIdRoute = StoreProductProductIdRouteImport.update({
  id: '/product/$productId',
  path: '/product/$productId',
  getParentRoute: () => StoreRoute,
} as any)
const StoreOrderOrderIdRoute = StoreOrderOrderIdRouteImport.update({
  id: '/order/$orderId',
  path: '/order/$orderId',
  getParentRoute: () => StoreRoute,
} as any)
const AdminStockTransfersRoute = AdminStockTransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => AdminStockRoute,
} as any)
const AdminStockHistoryRoute = AdminStockHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AdminStockRoute,
} as any)
const AdminStockExtractRoute = AdminStockExtractRouteImport.update({
  id: '/extract',
  path: '/extract',
  getParentRoute: () => AdminStockRoute,
} as any)
const AdminStockExitsRoute = AdminStockExitsRouteImport.update({
  id: '/exits',
  path: '/exits',
  getParentRoute: () => AdminStockRoute,
} as any)
const AdminStockEntriesRoute = AdminStockEntriesRouteImport.update({
  id: '/entries',
  path: '/entries',
  getParentRoute: () => AdminStockRoute,
} as any)
const AdminStockBalanceteRoute = AdminStockBalanceteRouteImport.update({
  id: '/balancete',
  path: '/balancete',
  getParentRoute: () => AdminStockRoute,
} as any)
const AdminStockBalanceRoute = AdminStockBalanceRouteImport.update({
  id: '/balance',
  path: '/balance',
  getParentRoute: () => AdminStockRoute,
} as any)
const AdminStockAdjustmentsRoute = AdminStockAdjustmentsRouteImport.update({
  id: '/adjustments',
  path: '/adjustments',
  getParentRoute: () => AdminStockRoute,
} as any)
const AdminFinancialSettingsRoute = AdminFinancialSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminFinancialRoute,
} as any)
const AdminFinancialSessionsRoute = AdminFinancialSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AdminFinancialRoute,
} as any)
const AdminFinancialReceivablesRoute =
  AdminFinancialReceivablesRouteImport.update({
    id: '/receivables',
    path: '/receivables',
    getParentRoute: () => AdminFinancialRoute,
  } as any)
const AdminFinancialPayablesRoute = AdminFinancialPayablesRouteImport.update({
  id: '/payables',
  path: '/payables',
  getParentRoute: () => AdminFinancialRoute,
} as any)
const AdminFinancialMovementsRoute = AdminFinancialMovementsRouteImport.update({
  id: '/movements',
  path: '/movements',
  getParentRoute: () => AdminFinancialRoute,
} as any)
const AdminFinancialHistoryRoute = AdminFinancialHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AdminFinancialRoute,
} as any)
const AdminFinancialDreRoute = AdminFinancialDreRouteImport.update({
  id: '/dre',
  path: '/dre',
  getParentRoute: () => AdminFinancialRoute,
} as any)
const AdminFinancialCashflowRoute = AdminFinancialCashflowRouteImport.update({
  id: '/cashflow',
  path: '/cashflow',
  getParentRoute: () => AdminFinancialRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/store': typeof StoreRouteWithChildren
  '/verify-email': typeof VerifyEmailRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/delivery': typeof AdminDeliveryRoute
  '/admin/financial': typeof AdminFinancialRouteWithChildren
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/pdv': typeof AdminPdvRoute
  '/admin/print-environments': typeof AdminPrintEnvironmentsRoute
  '/admin/printers': typeof AdminPrintersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reports-dashboard': typeof AdminReportsDashboardRoute
  '/admin/reports-preview': typeof AdminReportsPreviewRoute
  '/admin/sectors': typeof AdminSectorsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/stock': typeof AdminStockRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/loja/$slugOuId': typeof LojaSlugOuIdRoute
  '/store/account': typeof StoreAccountRoute
  '/store/cart': typeof StoreCartRoute
  '/store/categories': typeof StoreCategoriesRoute
  '/store/checkout': typeof StoreCheckoutRoute
  '/store/payment': typeof StorePaymentRoute
  '/store/search': typeof StoreSearchRoute
  '/admin/': typeof AdminIndexRoute
  '/store/': typeof StoreIndexRoute
  '/admin/financial/cashflow': typeof AdminFinancialCashflowRoute
  '/admin/financial/dre': typeof AdminFinancialDreRoute
  '/admin/financial/history': typeof AdminFinancialHistoryRoute
  '/admin/financial/movements': typeof AdminFinancialMovementsRoute
  '/admin/financial/payables': typeof AdminFinancialPayablesRoute
  '/admin/financial/receivables': typeof AdminFinancialReceivablesRoute
  '/admin/financial/sessions': typeof AdminFinancialSessionsRoute
  '/admin/financial/settings': typeof AdminFinancialSettingsRoute
  '/admin/stock/adjustments': typeof AdminStockAdjustmentsRoute
  '/admin/stock/balance': typeof AdminStockBalanceRoute
  '/admin/stock/balancete': typeof AdminStockBalanceteRoute
  '/admin/stock/entries': typeof AdminStockEntriesRoute
  '/admin/stock/exits': typeof AdminStockExitsRoute
  '/admin/stock/extract': typeof AdminStockExtractRoute
  '/admin/stock/history': typeof AdminStockHistoryRoute
  '/admin/stock/transfers': typeof AdminStockTransfersRoute
  '/store/order/$orderId': typeof StoreOrderOrderIdRoute
  '/store/product/$productId': typeof StoreProductProductIdRoute
  '/admin/financial/': typeof AdminFinancialIndexRoute
  '/admin/stock/': typeof AdminStockIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/delivery': typeof AdminDeliveryRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/pdv': typeof AdminPdvRoute
  '/admin/print-environments': typeof AdminPrintEnvironmentsRoute
  '/admin/printers': typeof AdminPrintersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reports-dashboard': typeof AdminReportsDashboardRoute
  '/admin/reports-preview': typeof AdminReportsPreviewRoute
  '/admin/sectors': typeof AdminSectorsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/loja/$slugOuId': typeof LojaSlugOuIdRoute
  '/store/account': typeof StoreAccountRoute
  '/store/cart': typeof StoreCartRoute
  '/store/categories': typeof StoreCategoriesRoute
  '/store/checkout': typeof StoreCheckoutRoute
  '/store/payment': typeof StorePaymentRoute
  '/store/search': typeof StoreSearchRoute
  '/admin': typeof AdminIndexRoute
  '/store': typeof StoreIndexRoute
  '/admin/financial/cashflow': typeof AdminFinancialCashflowRoute
  '/admin/financial/dre': typeof AdminFinancialDreRoute
  '/admin/financial/history': typeof AdminFinancialHistoryRoute
  '/admin/financial/movements': typeof AdminFinancialMovementsRoute
  '/admin/financial/payables': typeof AdminFinancialPayablesRoute
  '/admin/financial/receivables': typeof AdminFinancialReceivablesRoute
  '/admin/financial/sessions': typeof AdminFinancialSessionsRoute
  '/admin/financial/settings': typeof AdminFinancialSettingsRoute
  '/admin/stock/adjustments': typeof AdminStockAdjustmentsRoute
  '/admin/stock/balance': typeof AdminStockBalanceRoute
  '/admin/stock/balancete': typeof AdminStockBalanceteRoute
  '/admin/stock/entries': typeof AdminStockEntriesRoute
  '/admin/stock/exits': typeof AdminStockExitsRoute
  '/admin/stock/extract': typeof AdminStockExtractRoute
  '/admin/stock/history': typeof AdminStockHistoryRoute
  '/admin/stock/transfers': typeof AdminStockTransfersRoute
  '/store/order/$orderId': typeof StoreOrderOrderIdRoute
  '/store/product/$productId': typeof StoreProductProductIdRoute
  '/admin/financial': typeof AdminFinancialIndexRoute
  '/admin/stock': typeof AdminStockIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/store': typeof StoreRouteWithChildren
  '/verify-email': typeof VerifyEmailRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/delivery': typeof AdminDeliveryRoute
  '/admin/financial': typeof AdminFinancialRouteWithChildren
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/pdv': typeof AdminPdvRoute
  '/admin/print-environments': typeof AdminPrintEnvironmentsRoute
  '/admin/printers': typeof AdminPrintersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reports-dashboard': typeof AdminReportsDashboardRoute
  '/admin/reports-preview': typeof AdminReportsPreviewRoute
  '/admin/sectors': typeof AdminSectorsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/stock': typeof AdminStockRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/loja/$slugOuId': typeof LojaSlugOuIdRoute
  '/store/account': typeof StoreAccountRoute
  '/store/cart': typeof StoreCartRoute
  '/store/categories': typeof StoreCategoriesRoute
  '/store/checkout': typeof StoreCheckoutRoute
  '/store/payment': typeof StorePaymentRoute
  '/store/search': typeof StoreSearchRoute
  '/admin/': typeof AdminIndexRoute
  '/store/': typeof StoreIndexRoute
  '/admin/financial/cashflow': typeof AdminFinancialCashflowRoute
  '/admin/financial/dre': typeof AdminFinancialDreRoute
  '/admin/financial/history': typeof AdminFinancialHistoryRoute
  '/admin/financial/movements': typeof AdminFinancialMovementsRoute
  '/admin/financial/payables': typeof AdminFinancialPayablesRoute
  '/admin/financial/receivables': typeof AdminFinancialReceivablesRoute
  '/admin/financial/sessions': typeof AdminFinancialSessionsRoute
  '/admin/financial/settings': typeof AdminFinancialSettingsRoute
  '/admin/stock/adjustments': typeof AdminStockAdjustmentsRoute
  '/admin/stock/balance': typeof AdminStockBalanceRoute
  '/admin/stock/balancete': typeof AdminStockBalanceteRoute
  '/admin/stock/entries': typeof AdminStockEntriesRoute
  '/admin/stock/exits': typeof AdminStockExitsRoute
  '/admin/stock/extract': typeof AdminStockExtractRoute
  '/admin/stock/history': typeof AdminStockHistoryRoute
  '/admin/stock/transfers': typeof AdminStockTransfersRoute
  '/store/order/$orderId': typeof StoreOrderOrderIdRoute
  '/store/product/$productId': typeof StoreProductProductIdRoute
  '/admin/financial/': typeof AdminFinancialIndexRoute
  '/admin/stock/': typeof AdminStockIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/store'
    | '/verify-email'
    | '/admin/categories'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/delivery'
    | '/admin/financial'
    | '/admin/orders'
    | '/admin/pdv'
    | '/admin/print-environments'
    | '/admin/printers'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/reports-dashboard'
    | '/admin/reports-preview'
    | '/admin/sectors'
    | '/admin/settings'
    | '/admin/stock'
    | '/admin/users'
    | '/loja/$slugOuId'
    | '/store/account'
    | '/store/cart'
    | '/store/categories'
    | '/store/checkout'
    | '/store/payment'
    | '/store/search'
    | '/admin/'
    | '/store/'
    | '/admin/financial/cashflow'
    | '/admin/financial/dre'
    | '/admin/financial/history'
    | '/admin/financial/movements'
    | '/admin/financial/payables'
    | '/admin/financial/receivables'
    | '/admin/financial/sessions'
    | '/admin/financial/settings'
    | '/admin/stock/adjustments'
    | '/admin/stock/balance'
    | '/admin/stock/balancete'
    | '/admin/stock/entries'
    | '/admin/stock/exits'
    | '/admin/stock/extract'
    | '/admin/stock/history'
    | '/admin/stock/transfers'
    | '/store/order/$orderId'
    | '/store/product/$productId'
    | '/admin/financial/'
    | '/admin/stock/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/admin/categories'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/delivery'
    | '/admin/orders'
    | '/admin/pdv'
    | '/admin/print-environments'
    | '/admin/printers'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/reports-dashboard'
    | '/admin/reports-preview'
    | '/admin/sectors'
    | '/admin/settings'
    | '/admin/users'
    | '/loja/$slugOuId'
    | '/store/account'
    | '/store/cart'
    | '/store/categories'
    | '/store/checkout'
    | '/store/payment'
    | '/store/search'
    | '/admin'
    | '/store'
    | '/admin/financial/cashflow'
    | '/admin/financial/dre'
    | '/admin/financial/history'
    | '/admin/financial/movements'
    | '/admin/financial/payables'
    | '/admin/financial/receivables'
    | '/admin/financial/sessions'
    | '/admin/financial/settings'
    | '/admin/stock/adjustments'
    | '/admin/stock/balance'
    | '/admin/stock/balancete'
    | '/admin/stock/entries'
    | '/admin/stock/exits'
    | '/admin/stock/extract'
    | '/admin/stock/history'
    | '/admin/stock/transfers'
    | '/store/order/$orderId'
    | '/store/product/$productId'
    | '/admin/financial'
    | '/admin/stock'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/store'
    | '/verify-email'
    | '/admin/categories'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/delivery'
    | '/admin/financial'
    | '/admin/orders'
    | '/admin/pdv'
    | '/admin/print-environments'
    | '/admin/printers'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/reports-dashboard'
    | '/admin/reports-preview'
    | '/admin/sectors'
    | '/admin/settings'
    | '/admin/stock'
    | '/admin/users'
    | '/loja/$slugOuId'
    | '/store/account'
    | '/store/cart'
    | '/store/categories'
    | '/store/checkout'
    | '/store/payment'
    | '/store/search'
    | '/admin/'
    | '/store/'
    | '/admin/financial/cashflow'
    | '/admin/financial/dre'
    | '/admin/financial/history'
    | '/admin/financial/movements'
    | '/admin/financial/payables'
    | '/admin/financial/receivables'
    | '/admin/financial/sessions'
    | '/admin/financial/settings'
    | '/admin/stock/adjustments'
    | '/admin/stock/balance'
    | '/admin/stock/balancete'
    | '/admin/stock/entries'
    | '/admin/stock/exits'
    | '/admin/stock/extract'
    | '/admin/stock/history'
    | '/admin/stock/transfers'
    | '/store/order/$orderId'
    | '/store/product/$productId'
    | '/admin/financial/'
    | '/admin/stock/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  StoreRoute: typeof StoreRouteWithChildren
  VerifyEmailRoute: typeof VerifyEmailRoute
  LojaSlugOuIdRoute: typeof LojaSlugOuIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/': {
      id: '/store/'
      path: '/'
      fullPath: '/store/'
      preLoaderRoute: typeof StoreIndexRouteImport
      parentRoute: typeof StoreRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/store/search': {
      id: '/store/search'
      path: '/search'
      fullPath: '/store/search'
      preLoaderRoute: typeof StoreSearchRouteImport
      parentRoute: typeof StoreRoute
    }
    '/store/payment': {
      id: '/store/payment'
      path: '/payment'
      fullPath: '/store/payment'
      preLoaderRoute: typeof StorePaymentRouteImport
      parentRoute: typeof StoreRoute
    }
    '/store/checkout': {
      id: '/store/checkout'
      path: '/checkout'
      fullPath: '/store/checkout'
      preLoaderRoute: typeof StoreCheckoutRouteImport
      parentRoute: typeof StoreRoute
    }
    '/store/categories': {
      id: '/store/categories'
      path: '/categories'
      fullPath: '/store/categories'
      preLoaderRoute: typeof StoreCategoriesRouteImport
      parentRoute: typeof StoreRoute
    }
    '/store/cart': {
      id: '/store/cart'
      path: '/cart'
      fullPath: '/store/cart'
      preLoaderRoute: typeof StoreCartRouteImport
      parentRoute: typeof StoreRoute
    }
    '/store/account': {
      id: '/store/account'
      path: '/account'
      fullPath: '/store/account'
      preLoaderRoute: typeof StoreAccountRouteImport
      parentRoute: typeof StoreRoute
    }
    '/loja/$slugOuId': {
      id: '/loja/$slugOuId'
      path: '/loja/$slugOuId'
      fullPath: '/loja/$slugOuId'
      preLoaderRoute: typeof LojaSlugOuIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/stock': {
      id: '/admin/stock'
      path: '/stock'
      fullPath: '/admin/stock'
      preLoaderRoute: typeof AdminStockRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sectors': {
      id: '/admin/sectors'
      path: '/sectors'
      fullPath: '/admin/sectors'
      preLoaderRoute: typeof AdminSectorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports-preview': {
      id: '/admin/reports-preview'
      path: '/reports-preview'
      fullPath: '/admin/reports-preview'
      preLoaderRoute: typeof AdminReportsPreviewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports-dashboard': {
      id: '/admin/reports-dashboard'
      path: '/reports-dashboard'
      fullPath: '/admin/reports-dashboard'
      preLoaderRoute: typeof AdminReportsDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/printers': {
      id: '/admin/printers'
      path: '/printers'
      fullPath: '/admin/printers'
      preLoaderRoute: typeof AdminPrintersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/print-environments': {
      id: '/admin/print-environments'
      path: '/print-environments'
      fullPath: '/admin/print-environments'
      preLoaderRoute: typeof AdminPrintEnvironmentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pdv': {
      id: '/admin/pdv'
      path: '/pdv'
      fullPath: '/admin/pdv'
      preLoaderRoute: typeof AdminPdvRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/financial': {
      id: '/admin/financial'
      path: '/financial'
      fullPath: '/admin/financial'
      preLoaderRoute: typeof AdminFinancialRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/delivery': {
      id: '/admin/delivery'
      path: '/delivery'
      fullPath: '/admin/delivery'
      preLoaderRoute: typeof AdminDeliveryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/coupons': {
      id: '/admin/coupons'
      path: '/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AdminCouponsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/stock/': {
      id: '/admin/stock/'
      path: '/'
      fullPath: '/admin/stock/'
      preLoaderRoute: typeof AdminStockIndexRouteImport
      parentRoute: typeof AdminStockRoute
    }
    '/admin/financial/': {
      id: '/admin/financial/'
      path: '/'
      fullPath: '/admin/financial/'
      preLoaderRoute: typeof AdminFinancialIndexRouteImport
      parentRoute: typeof AdminFinancialRoute
    }
    '/store/product/$productId': {
      id: '/store/product/$productId'
      path: '/product/$productId'
      fullPath: '/store/product/$productId'
      preLoaderRoute: typeof StoreProductProductIdRouteImport
      parentRoute: typeof StoreRoute
    }
    '/store/order/$orderId': {
      id: '/store/order/$orderId'
      path: '/order/$orderId'
      fullPath: '/store/order/$orderId'
      preLoaderRoute: typeof StoreOrderOrderIdRouteImport
      parentRoute: typeof StoreRoute
    }
    '/admin/stock/transfers': {
      id: '/admin/stock/transfers'
      path: '/transfers'
      fullPath: '/admin/stock/transfers'
      preLoaderRoute: typeof AdminStockTransfersRouteImport
      parentRoute: typeof AdminStockRoute
    }
    '/admin/stock/history': {
      id: '/admin/stock/history'
      path: '/history'
      fullPath: '/admin/stock/history'
      preLoaderRoute: typeof AdminStockHistoryRouteImport
      parentRoute: typeof AdminStockRoute
    }
    '/admin/stock/extract': {
      id: '/admin/stock/extract'
      path: '/extract'
      fullPath: '/admin/stock/extract'
      preLoaderRoute: typeof AdminStockExtractRouteImport
      parentRoute: typeof AdminStockRoute
    }
    '/admin/stock/exits': {
      id: '/admin/stock/exits'
      path: '/exits'
      fullPath: '/admin/stock/exits'
      preLoaderRoute: typeof AdminStockExitsRouteImport
      parentRoute: typeof AdminStockRoute
    }
    '/admin/stock/entries': {
      id: '/admin/stock/entries'
      path: '/entries'
      fullPath: '/admin/stock/entries'
      preLoaderRoute: typeof AdminStockEntriesRouteImport
      parentRoute: typeof AdminStockRoute
    }
    '/admin/stock/balancete': {
      id: '/admin/stock/balancete'
      path: '/balancete'
      fullPath: '/admin/stock/balancete'
      preLoaderRoute: typeof AdminStockBalanceteRouteImport
      parentRoute: typeof AdminStockRoute
    }
    '/admin/stock/balance': {
      id: '/admin/stock/balance'
      path: '/balance'
      fullPath: '/admin/stock/balance'
      preLoaderRoute: typeof AdminStockBalanceRouteImport
      parentRoute: typeof AdminStockRoute
    }
    '/admin/stock/adjustments': {
      id: '/admin/stock/adjustments'
      path: '/adjustments'
      fullPath: '/admin/stock/adjustments'
      preLoaderRoute: typeof AdminStockAdjustmentsRouteImport
      parentRoute: typeof AdminStockRoute
    }
    '/admin/financial/settings': {
      id: '/admin/financial/settings'
      path: '/settings'
      fullPath: '/admin/financial/settings'
      preLoaderRoute: typeof AdminFinancialSettingsRouteImport
      parentRoute: typeof AdminFinancialRoute
    }
    '/admin/financial/sessions': {
      id: '/admin/financial/sessions'
      path: '/sessions'
      fullPath: '/admin/financial/sessions'
      preLoaderRoute: typeof AdminFinancialSessionsRouteImport
      parentRoute: typeof AdminFinancialRoute
    }
    '/admin/financial/receivables': {
      id: '/admin/financial/receivables'
      path: '/receivables'
      fullPath: '/admin/financial/receivables'
      preLoaderRoute: typeof AdminFinancialReceivablesRouteImport
      parentRoute: typeof AdminFinancialRoute
    }
    '/admin/financial/payables': {
      id: '/admin/financial/payables'
      path: '/payables'
      fullPath: '/admin/financial/payables'
      preLoaderRoute: typeof AdminFinancialPayablesRouteImport
      parentRoute: typeof AdminFinancialRoute
    }
    '/admin/financial/movements': {
      id: '/admin/financial/movements'
      path: '/movements'
      fullPath: '/admin/financial/movements'
      preLoaderRoute: typeof AdminFinancialMovementsRouteImport
      parentRoute: typeof AdminFinancialRoute
    }
    '/admin/financial/history': {
      id: '/admin/financial/history'
      path: '/history'
      fullPath: '/admin/financial/history'
      preLoaderRoute: typeof AdminFinancialHistoryRouteImport
      parentRoute: typeof AdminFinancialRoute
    }
    '/admin/financial/dre': {
      id: '/admin/financial/dre'
      path: '/dre'
      fullPath: '/admin/financial/dre'
      preLoaderRoute: typeof AdminFinancialDreRouteImport
      parentRoute: typeof AdminFinancialRoute
    }
    '/admin/financial/cashflow': {
      id: '/admin/financial/cashflow'
      path: '/cashflow'
      fullPath: '/admin/financial/cashflow'
      preLoaderRoute: typeof AdminFinancialCashflowRouteImport
      parentRoute: typeof AdminFinancialRoute
    }
  }
}

interface AdminFinancialRouteChildren {
  AdminFinancialCashflowRoute: typeof AdminFinancialCashflowRoute
  AdminFinancialDreRoute: typeof AdminFinancialDreRoute
  AdminFinancialHistoryRoute: typeof AdminFinancialHistoryRoute
  AdminFinancialMovementsRoute: typeof AdminFinancialMovementsRoute
  AdminFinancialPayablesRoute: typeof AdminFinancialPayablesRoute
  AdminFinancialReceivablesRoute: typeof AdminFinancialReceivablesRoute
  AdminFinancialSessionsRoute: typeof AdminFinancialSessionsRoute
  AdminFinancialSettingsRoute: typeof AdminFinancialSettingsRoute
  AdminFinancialIndexRoute: typeof AdminFinancialIndexRoute
}

const AdminFinancialRouteChildren: AdminFinancialRouteChildren = {
  AdminFinancialCashflowRoute: AdminFinancialCashflowRoute,
  AdminFinancialDreRoute: AdminFinancialDreRoute,
  AdminFinancialHistoryRoute: AdminFinancialHistoryRoute,
  AdminFinancialMovementsRoute: AdminFinancialMovementsRoute,
  AdminFinancialPayablesRoute: AdminFinancialPayablesRoute,
  AdminFinancialReceivablesRoute: AdminFinancialReceivablesRoute,
  AdminFinancialSessionsRoute: AdminFinancialSessionsRoute,
  AdminFinancialSettingsRoute: AdminFinancialSettingsRoute,
  AdminFinancialIndexRoute: AdminFinancialIndexRoute,
}

const AdminFinancialRouteWithChildren = AdminFinancialRoute._addFileChildren(
  AdminFinancialRouteChildren,
)

interface AdminStockRouteChildren {
  AdminStockAdjustmentsRoute: typeof AdminStockAdjustmentsRoute
  AdminStockBalanceRoute: typeof AdminStockBalanceRoute
  AdminStockBalanceteRoute: typeof AdminStockBalanceteRoute
  AdminStockEntriesRoute: typeof AdminStockEntriesRoute
  AdminStockExitsRoute: typeof AdminStockExitsRoute
  AdminStockExtractRoute: typeof AdminStockExtractRoute
  AdminStockHistoryRoute: typeof AdminStockHistoryRoute
  AdminStockTransfersRoute: typeof AdminStockTransfersRoute
  AdminStockIndexRoute: typeof AdminStockIndexRoute
}

const AdminStockRouteChildren: AdminStockRouteChildren = {
  AdminStockAdjustmentsRoute: AdminStockAdjustmentsRoute,
  AdminStockBalanceRoute: AdminStockBalanceRoute,
  AdminStockBalanceteRoute: AdminStockBalanceteRoute,
  AdminStockEntriesRoute: AdminStockEntriesRoute,
  AdminStockExitsRoute: AdminStockExitsRoute,
  AdminStockExtractRoute: AdminStockExtractRoute,
  AdminStockHistoryRoute: AdminStockHistoryRoute,
  AdminStockTransfersRoute: AdminStockTransfersRoute,
  AdminStockIndexRoute: AdminStockIndexRoute,
}

const AdminStockRouteWithChildren = AdminStockRoute._addFileChildren(
  AdminStockRouteChildren,
)

interface AdminRouteChildren {
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminCouponsRoute: typeof AdminCouponsRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminDeliveryRoute: typeof AdminDeliveryRoute
  AdminFinancialRoute: typeof AdminFinancialRouteWithChildren
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPdvRoute: typeof AdminPdvRoute
  AdminPrintEnvironmentsRoute: typeof AdminPrintEnvironmentsRoute
  AdminPrintersRoute: typeof AdminPrintersRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminReportsDashboardRoute: typeof AdminReportsDashboardRoute
  AdminReportsPreviewRoute: typeof AdminReportsPreviewRoute
  AdminSectorsRoute: typeof AdminSectorsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStockRoute: typeof AdminStockRouteWithChildren
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminCouponsRoute: AdminCouponsRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminDeliveryRoute: AdminDeliveryRoute,
  AdminFinancialRoute: AdminFinancialRouteWithChildren,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPdvRoute: AdminPdvRoute,
  AdminPrintEnvironmentsRoute: AdminPrintEnvironmentsRoute,
  AdminPrintersRoute: AdminPrintersRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminReportsDashboardRoute: AdminReportsDashboardRoute,
  AdminReportsPreviewRoute: AdminReportsPreviewRoute,
  AdminSectorsRoute: AdminSectorsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStockRoute: AdminStockRouteWithChildren,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface StoreRouteChildren {
  StoreAccountRoute: typeof StoreAccountRoute
  StoreCartRoute: typeof StoreCartRoute
  StoreCategoriesRoute: typeof StoreCategoriesRoute
  StoreCheckoutRoute: typeof StoreCheckoutRoute
  StorePaymentRoute: typeof StorePaymentRoute
  StoreSearchRoute: typeof StoreSearchRoute
  StoreIndexRoute: typeof StoreIndexRoute
  StoreOrderOrderIdRoute: typeof StoreOrderOrderIdRoute
  StoreProductProductIdRoute: typeof StoreProductProductIdRoute
}

const StoreRouteChildren: StoreRouteChildren = {
  StoreAccountRoute: StoreAccountRoute,
  StoreCartRoute: StoreCartRoute,
  StoreCategoriesRoute: StoreCategoriesRoute,
  StoreCheckoutRoute: StoreCheckoutRoute,
  StorePaymentRoute: StorePaymentRoute,
  StoreSearchRoute: StoreSearchRoute,
  StoreIndexRoute: StoreIndexRoute,
  StoreOrderOrderIdRoute: StoreOrderOrderIdRoute,
  StoreProductProductIdRoute: StoreProductProductIdRoute,
}

const StoreRouteWithChildren = StoreRoute._addFileChildren(StoreRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  StoreRoute: StoreRouteWithChildren,
  VerifyEmailRoute: VerifyEmailRoute,
  LojaSlugOuIdRoute: LojaSlugOuIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
