/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as TermosDeUsoRouteImport } from './routes/termos-de-uso'
import { Route as StoreRouteImport } from './routes/store'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ConviteRouteImport } from './routes/convite'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StoreIndexRouteImport } from './routes/store/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as StoreSearchRouteImport } from './routes/store/search'
import { Route as StorePaymentRouteImport } from './routes/store/payment'
import { Route as StoreCheckoutRouteImport } from './routes/store/checkout'
import { Route as StoreCategoriesRouteImport } from './routes/store/categories'
import { Route as StoreCartRouteImport } from './routes/store/cart'
import { Route as StoreAccountRouteImport } from './routes/store/account'
import { Route as LojaSlugOuIdRouteImport } from './routes/loja.$slugOuId'
import { Route as AdminUsuariosRouteImport } from './routes/admin/usuarios'
import { Route as AdminSetoresRouteImport } from './routes/admin/setores'
import { Route as AdminRelatoriosPreviewRouteImport } from './routes/admin/relatorios-preview'
import { Route as AdminRelatoriosDashboardRouteImport } from './routes/admin/relatorios-dashboard'
import { Route as AdminRelatoriosRouteImport } from './routes/admin/relatorios'
import { Route as AdminProdutosRouteImport } from './routes/admin/produtos'
import { Route as AdminPedidosRouteImport } from './routes/admin/pedidos'
import { Route as AdminPdvRouteImport } from './routes/admin/pdv'
import { Route as AdminImpressorasRouteImport } from './routes/admin/impressoras'
import { Route as AdminFinanceiroRouteImport } from './routes/admin/financeiro'
import { Route as AdminEstoqueRouteImport } from './routes/admin/estoque'
import { Route as AdminEntregaRouteImport } from './routes/admin/entrega'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminCuponsRouteImport } from './routes/admin/cupons'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin/configuracoes'
import { Route as AdminClientesRouteImport } from './routes/admin/clientes'
import { Route as AdminCategoriasRouteImport } from './routes/admin/categorias'
import { Route as AdminAmbientesImpressaoRouteImport } from './routes/admin/ambientes-impressao'
import { Route as AdminFinanceiroIndexRouteImport } from './routes/admin/financeiro/index'
import { Route as AdminEstoqueIndexRouteImport } from './routes/admin/estoque/index'
import { Route as StoreProductProductIdRouteImport } from './routes/store/product.$productId'
import { Route as StoreOrderOrderIdRouteImport } from './routes/store/order.$orderId'
import { Route as AdminFinanceiroSessoesRouteImport } from './routes/admin/financeiro/sessoes'
import { Route as AdminFinanceiroReceberRouteImport } from './routes/admin/financeiro/receber'
import { Route as AdminFinanceiroPagarRouteImport } from './routes/admin/financeiro/pagar'
import { Route as AdminFinanceiroMovimentacoesRouteImport } from './routes/admin/financeiro/movimentacoes'
import { Route as AdminFinanceiroHistoricoRouteImport } from './routes/admin/financeiro/historico'
import { Route as AdminFinanceiroFluxoCaixaRouteImport } from './routes/admin/financeiro/fluxo-caixa'
import { Route as AdminFinanceiroDreRouteImport } from './routes/admin/financeiro/dre'
import { Route as AdminFinanceiroConfiguracoesRouteImport } from './routes/admin/financeiro/configuracoes'
import { Route as AdminEstoqueTransferenciasRouteImport } from './routes/admin/estoque/transferencias'
import { Route as AdminEstoqueSaidasRouteImport } from './routes/admin/estoque/saidas'
import { Route as AdminEstoqueHistoricoRouteImport } from './routes/admin/estoque/historico'
import { Route as AdminEstoqueExtratoRouteImport } from './routes/admin/estoque/extrato'
import { Route as AdminEstoqueEntradasRouteImport } from './routes/admin/estoque/entradas'
import { Route as AdminEstoqueBalancoRouteImport } from './routes/admin/estoque/balanco'
import { Route as AdminEstoqueBalanceteRouteImport } from './routes/admin/estoque/balancete'
import { Route as AdminEstoqueAjustesRouteImport } from './routes/admin/estoque/ajustes'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosDeUsoRoute = TermosDeUsoRouteImport.update({
  id: '/termos-de-uso',
  path: '/termos-de-uso',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ConviteRoute = ConviteRouteImport.update({
  id: '/convite',
  path: '/convite',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreIndexRoute = StoreIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StoreRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const StoreSearchRoute = StoreSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => StoreRoute,
} as any)
const StorePaymentRoute = StorePaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => StoreRoute,
} as any)
const StoreCheckoutRoute = StoreCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => StoreRoute,
} as any)
const StoreCategoriesRoute = StoreCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => StoreRoute,
} as any)
const StoreCartRoute = StoreCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => StoreRoute,
} as any)
const StoreAccountRoute = StoreAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => StoreRoute,
} as any)
const LojaSlugOuIdRoute = LojaSlugOuIdRouteImport.update({
  id: '/loja/$slugOuId',
  path: '/loja/$slugOuId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSetoresRoute = AdminSetoresRouteImport.update({
  id: '/setores',
  path: '/setores',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRelatoriosPreviewRoute = AdminRelatoriosPreviewRouteImport.update({
  id: '/relatorios-preview',
  path: '/relatorios-preview',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRelatoriosDashboardRoute =
  AdminRelatoriosDashboardRouteImport.update({
    id: '/relatorios-dashboard',
    path: '/relatorios-dashboard',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminRelatoriosRoute = AdminRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProdutosRoute = AdminProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPedidosRoute = AdminPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPdvRoute = AdminPdvRouteImport.update({
  id: '/pdv',
  path: '/pdv',
  getParentRoute: () => AdminRoute,
} as any)
const AdminImpressorasRoute = AdminImpressorasRouteImport.update({
  id: '/impressoras',
  path: '/impressoras',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceiroRoute = AdminFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEstoqueRoute = AdminEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEntregaRoute = AdminEntregaRouteImport.update({
  id: '/entrega',
  path: '/entrega',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCuponsRoute = AdminCuponsRouteImport.update({
  id: '/cupons',
  path: '/cupons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientesRoute = AdminClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriasRoute = AdminCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAmbientesImpressaoRoute = AdminAmbientesImpressaoRouteImport.update({
  id: '/ambientes-impressao',
  path: '/ambientes-impressao',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceiroIndexRoute = AdminFinanceiroIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminFinanceiroRoute,
} as any)
const AdminEstoqueIndexRoute = AdminEstoqueIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminEstoqueRoute,
} as any)
const StoreProductProductIdRoute = StoreProductProductIdRouteImport.update({
  id: '/product/$productId',
  path: '/product/$productId',
  getParentRoute: () => StoreRoute,
} as any)
const StoreOrderOrderIdRoute = StoreOrderOrderIdRouteImport.update({
  id: '/order/$orderId',
  path: '/order/$orderId',
  getParentRoute: () => StoreRoute,
} as any)
const AdminFinanceiroSessoesRoute = AdminFinanceiroSessoesRouteImport.update({
  id: '/sessoes',
  path: '/sessoes',
  getParentRoute: () => AdminFinanceiroRoute,
} as any)
const AdminFinanceiroReceberRoute = AdminFinanceiroReceberRouteImport.update({
  id: '/receber',
  path: '/receber',
  getParentRoute: () => AdminFinanceiroRoute,
} as any)
const AdminFinanceiroPagarRoute = AdminFinanceiroPagarRouteImport.update({
  id: '/pagar',
  path: '/pagar',
  getParentRoute: () => AdminFinanceiroRoute,
} as any)
const AdminFinanceiroMovimentacoesRoute =
  AdminFinanceiroMovimentacoesRouteImport.update({
    id: '/movimentacoes',
    path: '/movimentacoes',
    getParentRoute: () => AdminFinanceiroRoute,
  } as any)
const AdminFinanceiroHistoricoRoute =
  AdminFinanceiroHistoricoRouteImport.update({
    id: '/historico',
    path: '/historico',
    getParentRoute: () => AdminFinanceiroRoute,
  } as any)
const AdminFinanceiroFluxoCaixaRoute =
  AdminFinanceiroFluxoCaixaRouteImport.update({
    id: '/fluxo-caixa',
    path: '/fluxo-caixa',
    getParentRoute: () => AdminFinanceiroRoute,
  } as any)
const AdminFinanceiroDreRoute = AdminFinanceiroDreRouteImport.update({
  id: '/dre',
  path: '/dre',
  getParentRoute: () => AdminFinanceiroRoute,
} as any)
const AdminFinanceiroConfiguracoesRoute =
  AdminFinanceiroConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AdminFinanceiroRoute,
  } as any)
const AdminEstoqueTransferenciasRoute =
  AdminEstoqueTransferenciasRouteImport.update({
    id: '/transferencias',
    path: '/transferencias',
    getParentRoute: () => AdminEstoqueRoute,
  } as any)
const AdminEstoqueSaidasRoute = AdminEstoqueSaidasRouteImport.update({
  id: '/saidas',
  path: '/saidas',
  getParentRoute: () => AdminEstoqueRoute,
} as any)
const AdminEstoqueHistoricoRoute = AdminEstoqueHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AdminEstoqueRoute,
} as any)
const AdminEstoqueExtratoRoute = AdminEstoqueExtratoRouteImport.update({
  id: '/extrato',
  path: '/extrato',
  getParentRoute: () => AdminEstoqueRoute,
} as any)
const AdminEstoqueEntradasRoute = AdminEstoqueEntradasRouteImport.update({
  id: '/entradas',
  path: '/entradas',
  getParentRoute: () => AdminEstoqueRoute,
} as any)
const AdminEstoqueBalancoRoute = AdminEstoqueBalancoRouteImport.update({
  id: '/balanco',
  path: '/balanco',
  getParentRoute: () => AdminEstoqueRoute,
} as any)
const AdminEstoqueBalanceteRoute = AdminEstoqueBalanceteRouteImport.update({
  id: '/balancete',
  path: '/balancete',
  getParentRoute: () => AdminEstoqueRoute,
} as any)
const AdminEstoqueAjustesRoute = AdminEstoqueAjustesRouteImport.update({
  id: '/ajustes',
  path: '/ajustes',
  getParentRoute: () => AdminEstoqueRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/convite': typeof ConviteRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/store': typeof StoreRouteWithChildren
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/ambientes-impressao': typeof AdminAmbientesImpressaoRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/cupons': typeof AdminCuponsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/entrega': typeof AdminEntregaRoute
  '/admin/estoque': typeof AdminEstoqueRouteWithChildren
  '/admin/financeiro': typeof AdminFinanceiroRouteWithChildren
  '/admin/impressoras': typeof AdminImpressorasRoute
  '/admin/pdv': typeof AdminPdvRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/relatorios-dashboard': typeof AdminRelatoriosDashboardRoute
  '/admin/relatorios-preview': typeof AdminRelatoriosPreviewRoute
  '/admin/setores': typeof AdminSetoresRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/loja/$slugOuId': typeof LojaSlugOuIdRoute
  '/store/account': typeof StoreAccountRoute
  '/store/cart': typeof StoreCartRoute
  '/store/categories': typeof StoreCategoriesRoute
  '/store/checkout': typeof StoreCheckoutRoute
  '/store/payment': typeof StorePaymentRoute
  '/store/search': typeof StoreSearchRoute
  '/admin/': typeof AdminIndexRoute
  '/store/': typeof StoreIndexRoute
  '/admin/estoque/ajustes': typeof AdminEstoqueAjustesRoute
  '/admin/estoque/balancete': typeof AdminEstoqueBalanceteRoute
  '/admin/estoque/balanco': typeof AdminEstoqueBalancoRoute
  '/admin/estoque/entradas': typeof AdminEstoqueEntradasRoute
  '/admin/estoque/extrato': typeof AdminEstoqueExtratoRoute
  '/admin/estoque/historico': typeof AdminEstoqueHistoricoRoute
  '/admin/estoque/saidas': typeof AdminEstoqueSaidasRoute
  '/admin/estoque/transferencias': typeof AdminEstoqueTransferenciasRoute
  '/admin/financeiro/configuracoes': typeof AdminFinanceiroConfiguracoesRoute
  '/admin/financeiro/dre': typeof AdminFinanceiroDreRoute
  '/admin/financeiro/fluxo-caixa': typeof AdminFinanceiroFluxoCaixaRoute
  '/admin/financeiro/historico': typeof AdminFinanceiroHistoricoRoute
  '/admin/financeiro/movimentacoes': typeof AdminFinanceiroMovimentacoesRoute
  '/admin/financeiro/pagar': typeof AdminFinanceiroPagarRoute
  '/admin/financeiro/receber': typeof AdminFinanceiroReceberRoute
  '/admin/financeiro/sessoes': typeof AdminFinanceiroSessoesRoute
  '/store/order/$orderId': typeof StoreOrderOrderIdRoute
  '/store/product/$productId': typeof StoreProductProductIdRoute
  '/admin/estoque/': typeof AdminEstoqueIndexRoute
  '/admin/financeiro/': typeof AdminFinanceiroIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/convite': typeof ConviteRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/ambientes-impressao': typeof AdminAmbientesImpressaoRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/cupons': typeof AdminCuponsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/entrega': typeof AdminEntregaRoute
  '/admin/impressoras': typeof AdminImpressorasRoute
  '/admin/pdv': typeof AdminPdvRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/relatorios-dashboard': typeof AdminRelatoriosDashboardRoute
  '/admin/relatorios-preview': typeof AdminRelatoriosPreviewRoute
  '/admin/setores': typeof AdminSetoresRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/loja/$slugOuId': typeof LojaSlugOuIdRoute
  '/store/account': typeof StoreAccountRoute
  '/store/cart': typeof StoreCartRoute
  '/store/categories': typeof StoreCategoriesRoute
  '/store/checkout': typeof StoreCheckoutRoute
  '/store/payment': typeof StorePaymentRoute
  '/store/search': typeof StoreSearchRoute
  '/admin': typeof AdminIndexRoute
  '/store': typeof StoreIndexRoute
  '/admin/estoque/ajustes': typeof AdminEstoqueAjustesRoute
  '/admin/estoque/balancete': typeof AdminEstoqueBalanceteRoute
  '/admin/estoque/balanco': typeof AdminEstoqueBalancoRoute
  '/admin/estoque/entradas': typeof AdminEstoqueEntradasRoute
  '/admin/estoque/extrato': typeof AdminEstoqueExtratoRoute
  '/admin/estoque/historico': typeof AdminEstoqueHistoricoRoute
  '/admin/estoque/saidas': typeof AdminEstoqueSaidasRoute
  '/admin/estoque/transferencias': typeof AdminEstoqueTransferenciasRoute
  '/admin/financeiro/configuracoes': typeof AdminFinanceiroConfiguracoesRoute
  '/admin/financeiro/dre': typeof AdminFinanceiroDreRoute
  '/admin/financeiro/fluxo-caixa': typeof AdminFinanceiroFluxoCaixaRoute
  '/admin/financeiro/historico': typeof AdminFinanceiroHistoricoRoute
  '/admin/financeiro/movimentacoes': typeof AdminFinanceiroMovimentacoesRoute
  '/admin/financeiro/pagar': typeof AdminFinanceiroPagarRoute
  '/admin/financeiro/receber': typeof AdminFinanceiroReceberRoute
  '/admin/financeiro/sessoes': typeof AdminFinanceiroSessoesRoute
  '/store/order/$orderId': typeof StoreOrderOrderIdRoute
  '/store/product/$productId': typeof StoreProductProductIdRoute
  '/admin/estoque': typeof AdminEstoqueIndexRoute
  '/admin/financeiro': typeof AdminFinanceiroIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/convite': typeof ConviteRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/store': typeof StoreRouteWithChildren
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/ambientes-impressao': typeof AdminAmbientesImpressaoRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/cupons': typeof AdminCuponsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/entrega': typeof AdminEntregaRoute
  '/admin/estoque': typeof AdminEstoqueRouteWithChildren
  '/admin/financeiro': typeof AdminFinanceiroRouteWithChildren
  '/admin/impressoras': typeof AdminImpressorasRoute
  '/admin/pdv': typeof AdminPdvRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/relatorios-dashboard': typeof AdminRelatoriosDashboardRoute
  '/admin/relatorios-preview': typeof AdminRelatoriosPreviewRoute
  '/admin/setores': typeof AdminSetoresRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/loja/$slugOuId': typeof LojaSlugOuIdRoute
  '/store/account': typeof StoreAccountRoute
  '/store/cart': typeof StoreCartRoute
  '/store/categories': typeof StoreCategoriesRoute
  '/store/checkout': typeof StoreCheckoutRoute
  '/store/payment': typeof StorePaymentRoute
  '/store/search': typeof StoreSearchRoute
  '/admin/': typeof AdminIndexRoute
  '/store/': typeof StoreIndexRoute
  '/admin/estoque/ajustes': typeof AdminEstoqueAjustesRoute
  '/admin/estoque/balancete': typeof AdminEstoqueBalanceteRoute
  '/admin/estoque/balanco': typeof AdminEstoqueBalancoRoute
  '/admin/estoque/entradas': typeof AdminEstoqueEntradasRoute
  '/admin/estoque/extrato': typeof AdminEstoqueExtratoRoute
  '/admin/estoque/historico': typeof AdminEstoqueHistoricoRoute
  '/admin/estoque/saidas': typeof AdminEstoqueSaidasRoute
  '/admin/estoque/transferencias': typeof AdminEstoqueTransferenciasRoute
  '/admin/financeiro/configuracoes': typeof AdminFinanceiroConfiguracoesRoute
  '/admin/financeiro/dre': typeof AdminFinanceiroDreRoute
  '/admin/financeiro/fluxo-caixa': typeof AdminFinanceiroFluxoCaixaRoute
  '/admin/financeiro/historico': typeof AdminFinanceiroHistoricoRoute
  '/admin/financeiro/movimentacoes': typeof AdminFinanceiroMovimentacoesRoute
  '/admin/financeiro/pagar': typeof AdminFinanceiroPagarRoute
  '/admin/financeiro/receber': typeof AdminFinanceiroReceberRoute
  '/admin/financeiro/sessoes': typeof AdminFinanceiroSessoesRoute
  '/store/order/$orderId': typeof StoreOrderOrderIdRoute
  '/store/product/$productId': typeof StoreProductProductIdRoute
  '/admin/estoque/': typeof AdminEstoqueIndexRoute
  '/admin/financeiro/': typeof AdminFinanceiroIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/convite'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/store'
    | '/termos-de-uso'
    | '/verify-email'
    | '/admin/ambientes-impressao'
    | '/admin/categorias'
    | '/admin/clientes'
    | '/admin/configuracoes'
    | '/admin/cupons'
    | '/admin/dashboard'
    | '/admin/entrega'
    | '/admin/estoque'
    | '/admin/financeiro'
    | '/admin/impressoras'
    | '/admin/pdv'
    | '/admin/pedidos'
    | '/admin/produtos'
    | '/admin/relatorios'
    | '/admin/relatorios-dashboard'
    | '/admin/relatorios-preview'
    | '/admin/setores'
    | '/admin/usuarios'
    | '/loja/$slugOuId'
    | '/store/account'
    | '/store/cart'
    | '/store/categories'
    | '/store/checkout'
    | '/store/payment'
    | '/store/search'
    | '/admin/'
    | '/store/'
    | '/admin/estoque/ajustes'
    | '/admin/estoque/balancete'
    | '/admin/estoque/balanco'
    | '/admin/estoque/entradas'
    | '/admin/estoque/extrato'
    | '/admin/estoque/historico'
    | '/admin/estoque/saidas'
    | '/admin/estoque/transferencias'
    | '/admin/financeiro/configuracoes'
    | '/admin/financeiro/dre'
    | '/admin/financeiro/fluxo-caixa'
    | '/admin/financeiro/historico'
    | '/admin/financeiro/movimentacoes'
    | '/admin/financeiro/pagar'
    | '/admin/financeiro/receber'
    | '/admin/financeiro/sessoes'
    | '/store/order/$orderId'
    | '/store/product/$productId'
    | '/admin/estoque/'
    | '/admin/financeiro/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/convite'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/termos-de-uso'
    | '/verify-email'
    | '/admin/ambientes-impressao'
    | '/admin/categorias'
    | '/admin/clientes'
    | '/admin/configuracoes'
    | '/admin/cupons'
    | '/admin/dashboard'
    | '/admin/entrega'
    | '/admin/impressoras'
    | '/admin/pdv'
    | '/admin/pedidos'
    | '/admin/produtos'
    | '/admin/relatorios'
    | '/admin/relatorios-dashboard'
    | '/admin/relatorios-preview'
    | '/admin/setores'
    | '/admin/usuarios'
    | '/loja/$slugOuId'
    | '/store/account'
    | '/store/cart'
    | '/store/categories'
    | '/store/checkout'
    | '/store/payment'
    | '/store/search'
    | '/admin'
    | '/store'
    | '/admin/estoque/ajustes'
    | '/admin/estoque/balancete'
    | '/admin/estoque/balanco'
    | '/admin/estoque/entradas'
    | '/admin/estoque/extrato'
    | '/admin/estoque/historico'
    | '/admin/estoque/saidas'
    | '/admin/estoque/transferencias'
    | '/admin/financeiro/configuracoes'
    | '/admin/financeiro/dre'
    | '/admin/financeiro/fluxo-caixa'
    | '/admin/financeiro/historico'
    | '/admin/financeiro/movimentacoes'
    | '/admin/financeiro/pagar'
    | '/admin/financeiro/receber'
    | '/admin/financeiro/sessoes'
    | '/store/order/$orderId'
    | '/store/product/$productId'
    | '/admin/estoque'
    | '/admin/financeiro'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/convite'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/store'
    | '/termos-de-uso'
    | '/verify-email'
    | '/admin/ambientes-impressao'
    | '/admin/categorias'
    | '/admin/clientes'
    | '/admin/configuracoes'
    | '/admin/cupons'
    | '/admin/dashboard'
    | '/admin/entrega'
    | '/admin/estoque'
    | '/admin/financeiro'
    | '/admin/impressoras'
    | '/admin/pdv'
    | '/admin/pedidos'
    | '/admin/produtos'
    | '/admin/relatorios'
    | '/admin/relatorios-dashboard'
    | '/admin/relatorios-preview'
    | '/admin/setores'
    | '/admin/usuarios'
    | '/loja/$slugOuId'
    | '/store/account'
    | '/store/cart'
    | '/store/categories'
    | '/store/checkout'
    | '/store/payment'
    | '/store/search'
    | '/admin/'
    | '/store/'
    | '/admin/estoque/ajustes'
    | '/admin/estoque/balancete'
    | '/admin/estoque/balanco'
    | '/admin/estoque/entradas'
    | '/admin/estoque/extrato'
    | '/admin/estoque/historico'
    | '/admin/estoque/saidas'
    | '/admin/estoque/transferencias'
    | '/admin/financeiro/configuracoes'
    | '/admin/financeiro/dre'
    | '/admin/financeiro/fluxo-caixa'
    | '/admin/financeiro/historico'
    | '/admin/financeiro/movimentacoes'
    | '/admin/financeiro/pagar'
    | '/admin/financeiro/receber'
    | '/admin/financeiro/sessoes'
    | '/store/order/$orderId'
    | '/store/product/$productId'
    | '/admin/estoque/'
    | '/admin/financeiro/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ConviteRoute: typeof ConviteRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  StoreRoute: typeof StoreRouteWithChildren
  TermosDeUsoRoute: typeof TermosDeUsoRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  LojaSlugOuIdRoute: typeof LojaSlugOuIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos-de-uso': {
      id: '/termos-de-uso'
      path: '/termos-de-uso'
      fullPath: '/termos-de-uso'
      preLoaderRoute: typeof TermosDeUsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convite': {
      id: '/convite'
      path: '/convite'
      fullPath: '/convite'
      preLoaderRoute: typeof ConviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/': {
      id: '/store/'
      path: '/'
      fullPath: '/store/'
      preLoaderRoute: typeof StoreIndexRouteImport
      parentRoute: typeof StoreRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/store/search': {
      id: '/store/search'
      path: '/search'
      fullPath: '/store/search'
      preLoaderRoute: typeof StoreSearchRouteImport
      parentRoute: typeof StoreRoute
    }
    '/store/payment': {
      id: '/store/payment'
      path: '/payment'
      fullPath: '/store/payment'
      preLoaderRoute: typeof StorePaymentRouteImport
      parentRoute: typeof StoreRoute
    }
    '/store/checkout': {
      id: '/store/checkout'
      path: '/checkout'
      fullPath: '/store/checkout'
      preLoaderRoute: typeof StoreCheckoutRouteImport
      parentRoute: typeof StoreRoute
    }
    '/store/categories': {
      id: '/store/categories'
      path: '/categories'
      fullPath: '/store/categories'
      preLoaderRoute: typeof StoreCategoriesRouteImport
      parentRoute: typeof StoreRoute
    }
    '/store/cart': {
      id: '/store/cart'
      path: '/cart'
      fullPath: '/store/cart'
      preLoaderRoute: typeof StoreCartRouteImport
      parentRoute: typeof StoreRoute
    }
    '/store/account': {
      id: '/store/account'
      path: '/account'
      fullPath: '/store/account'
      preLoaderRoute: typeof StoreAccountRouteImport
      parentRoute: typeof StoreRoute
    }
    '/loja/$slugOuId': {
      id: '/loja/$slugOuId'
      path: '/loja/$slugOuId'
      fullPath: '/loja/$slugOuId'
      preLoaderRoute: typeof LojaSlugOuIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/setores': {
      id: '/admin/setores'
      path: '/setores'
      fullPath: '/admin/setores'
      preLoaderRoute: typeof AdminSetoresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/relatorios-preview': {
      id: '/admin/relatorios-preview'
      path: '/relatorios-preview'
      fullPath: '/admin/relatorios-preview'
      preLoaderRoute: typeof AdminRelatoriosPreviewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/relatorios-dashboard': {
      id: '/admin/relatorios-dashboard'
      path: '/relatorios-dashboard'
      fullPath: '/admin/relatorios-dashboard'
      preLoaderRoute: typeof AdminRelatoriosDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/relatorios': {
      id: '/admin/relatorios'
      path: '/relatorios'
      fullPath: '/admin/relatorios'
      preLoaderRoute: typeof AdminRelatoriosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/produtos': {
      id: '/admin/produtos'
      path: '/produtos'
      fullPath: '/admin/produtos'
      preLoaderRoute: typeof AdminProdutosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pedidos': {
      id: '/admin/pedidos'
      path: '/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AdminPedidosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pdv': {
      id: '/admin/pdv'
      path: '/pdv'
      fullPath: '/admin/pdv'
      preLoaderRoute: typeof AdminPdvRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/impressoras': {
      id: '/admin/impressoras'
      path: '/impressoras'
      fullPath: '/admin/impressoras'
      preLoaderRoute: typeof AdminImpressorasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/financeiro': {
      id: '/admin/financeiro'
      path: '/financeiro'
      fullPath: '/admin/financeiro'
      preLoaderRoute: typeof AdminFinanceiroRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/estoque': {
      id: '/admin/estoque'
      path: '/estoque'
      fullPath: '/admin/estoque'
      preLoaderRoute: typeof AdminEstoqueRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/entrega': {
      id: '/admin/entrega'
      path: '/entrega'
      fullPath: '/admin/entrega'
      preLoaderRoute: typeof AdminEntregaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cupons': {
      id: '/admin/cupons'
      path: '/cupons'
      fullPath: '/admin/cupons'
      preLoaderRoute: typeof AdminCuponsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracoes': {
      id: '/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clientes': {
      id: '/admin/clientes'
      path: '/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AdminClientesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categorias': {
      id: '/admin/categorias'
      path: '/categorias'
      fullPath: '/admin/categorias'
      preLoaderRoute: typeof AdminCategoriasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ambientes-impressao': {
      id: '/admin/ambientes-impressao'
      path: '/ambientes-impressao'
      fullPath: '/admin/ambientes-impressao'
      preLoaderRoute: typeof AdminAmbientesImpressaoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/financeiro/': {
      id: '/admin/financeiro/'
      path: '/'
      fullPath: '/admin/financeiro/'
      preLoaderRoute: typeof AdminFinanceiroIndexRouteImport
      parentRoute: typeof AdminFinanceiroRoute
    }
    '/admin/estoque/': {
      id: '/admin/estoque/'
      path: '/'
      fullPath: '/admin/estoque/'
      preLoaderRoute: typeof AdminEstoqueIndexRouteImport
      parentRoute: typeof AdminEstoqueRoute
    }
    '/store/product/$productId': {
      id: '/store/product/$productId'
      path: '/product/$productId'
      fullPath: '/store/product/$productId'
      preLoaderRoute: typeof StoreProductProductIdRouteImport
      parentRoute: typeof StoreRoute
    }
    '/store/order/$orderId': {
      id: '/store/order/$orderId'
      path: '/order/$orderId'
      fullPath: '/store/order/$orderId'
      preLoaderRoute: typeof StoreOrderOrderIdRouteImport
      parentRoute: typeof StoreRoute
    }
    '/admin/financeiro/sessoes': {
      id: '/admin/financeiro/sessoes'
      path: '/sessoes'
      fullPath: '/admin/financeiro/sessoes'
      preLoaderRoute: typeof AdminFinanceiroSessoesRouteImport
      parentRoute: typeof AdminFinanceiroRoute
    }
    '/admin/financeiro/receber': {
      id: '/admin/financeiro/receber'
      path: '/receber'
      fullPath: '/admin/financeiro/receber'
      preLoaderRoute: typeof AdminFinanceiroReceberRouteImport
      parentRoute: typeof AdminFinanceiroRoute
    }
    '/admin/financeiro/pagar': {
      id: '/admin/financeiro/pagar'
      path: '/pagar'
      fullPath: '/admin/financeiro/pagar'
      preLoaderRoute: typeof AdminFinanceiroPagarRouteImport
      parentRoute: typeof AdminFinanceiroRoute
    }
    '/admin/financeiro/movimentacoes': {
      id: '/admin/financeiro/movimentacoes'
      path: '/movimentacoes'
      fullPath: '/admin/financeiro/movimentacoes'
      preLoaderRoute: typeof AdminFinanceiroMovimentacoesRouteImport
      parentRoute: typeof AdminFinanceiroRoute
    }
    '/admin/financeiro/historico': {
      id: '/admin/financeiro/historico'
      path: '/historico'
      fullPath: '/admin/financeiro/historico'
      preLoaderRoute: typeof AdminFinanceiroHistoricoRouteImport
      parentRoute: typeof AdminFinanceiroRoute
    }
    '/admin/financeiro/fluxo-caixa': {
      id: '/admin/financeiro/fluxo-caixa'
      path: '/fluxo-caixa'
      fullPath: '/admin/financeiro/fluxo-caixa'
      preLoaderRoute: typeof AdminFinanceiroFluxoCaixaRouteImport
      parentRoute: typeof AdminFinanceiroRoute
    }
    '/admin/financeiro/dre': {
      id: '/admin/financeiro/dre'
      path: '/dre'
      fullPath: '/admin/financeiro/dre'
      preLoaderRoute: typeof AdminFinanceiroDreRouteImport
      parentRoute: typeof AdminFinanceiroRoute
    }
    '/admin/financeiro/configuracoes': {
      id: '/admin/financeiro/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/financeiro/configuracoes'
      preLoaderRoute: typeof AdminFinanceiroConfiguracoesRouteImport
      parentRoute: typeof AdminFinanceiroRoute
    }
    '/admin/estoque/transferencias': {
      id: '/admin/estoque/transferencias'
      path: '/transferencias'
      fullPath: '/admin/estoque/transferencias'
      preLoaderRoute: typeof AdminEstoqueTransferenciasRouteImport
      parentRoute: typeof AdminEstoqueRoute
    }
    '/admin/estoque/saidas': {
      id: '/admin/estoque/saidas'
      path: '/saidas'
      fullPath: '/admin/estoque/saidas'
      preLoaderRoute: typeof AdminEstoqueSaidasRouteImport
      parentRoute: typeof AdminEstoqueRoute
    }
    '/admin/estoque/historico': {
      id: '/admin/estoque/historico'
      path: '/historico'
      fullPath: '/admin/estoque/historico'
      preLoaderRoute: typeof AdminEstoqueHistoricoRouteImport
      parentRoute: typeof AdminEstoqueRoute
    }
    '/admin/estoque/extrato': {
      id: '/admin/estoque/extrato'
      path: '/extrato'
      fullPath: '/admin/estoque/extrato'
      preLoaderRoute: typeof AdminEstoqueExtratoRouteImport
      parentRoute: typeof AdminEstoqueRoute
    }
    '/admin/estoque/entradas': {
      id: '/admin/estoque/entradas'
      path: '/entradas'
      fullPath: '/admin/estoque/entradas'
      preLoaderRoute: typeof AdminEstoqueEntradasRouteImport
      parentRoute: typeof AdminEstoqueRoute
    }
    '/admin/estoque/balanco': {
      id: '/admin/estoque/balanco'
      path: '/balanco'
      fullPath: '/admin/estoque/balanco'
      preLoaderRoute: typeof AdminEstoqueBalancoRouteImport
      parentRoute: typeof AdminEstoqueRoute
    }
    '/admin/estoque/balancete': {
      id: '/admin/estoque/balancete'
      path: '/balancete'
      fullPath: '/admin/estoque/balancete'
      preLoaderRoute: typeof AdminEstoqueBalanceteRouteImport
      parentRoute: typeof AdminEstoqueRoute
    }
    '/admin/estoque/ajustes': {
      id: '/admin/estoque/ajustes'
      path: '/ajustes'
      fullPath: '/admin/estoque/ajustes'
      preLoaderRoute: typeof AdminEstoqueAjustesRouteImport
      parentRoute: typeof AdminEstoqueRoute
    }
  }
}

interface AdminEstoqueRouteChildren {
  AdminEstoqueAjustesRoute: typeof AdminEstoqueAjustesRoute
  AdminEstoqueBalanceteRoute: typeof AdminEstoqueBalanceteRoute
  AdminEstoqueBalancoRoute: typeof AdminEstoqueBalancoRoute
  AdminEstoqueEntradasRoute: typeof AdminEstoqueEntradasRoute
  AdminEstoqueExtratoRoute: typeof AdminEstoqueExtratoRoute
  AdminEstoqueHistoricoRoute: typeof AdminEstoqueHistoricoRoute
  AdminEstoqueSaidasRoute: typeof AdminEstoqueSaidasRoute
  AdminEstoqueTransferenciasRoute: typeof AdminEstoqueTransferenciasRoute
  AdminEstoqueIndexRoute: typeof AdminEstoqueIndexRoute
}

const AdminEstoqueRouteChildren: AdminEstoqueRouteChildren = {
  AdminEstoqueAjustesRoute: AdminEstoqueAjustesRoute,
  AdminEstoqueBalanceteRoute: AdminEstoqueBalanceteRoute,
  AdminEstoqueBalancoRoute: AdminEstoqueBalancoRoute,
  AdminEstoqueEntradasRoute: AdminEstoqueEntradasRoute,
  AdminEstoqueExtratoRoute: AdminEstoqueExtratoRoute,
  AdminEstoqueHistoricoRoute: AdminEstoqueHistoricoRoute,
  AdminEstoqueSaidasRoute: AdminEstoqueSaidasRoute,
  AdminEstoqueTransferenciasRoute: AdminEstoqueTransferenciasRoute,
  AdminEstoqueIndexRoute: AdminEstoqueIndexRoute,
}

const AdminEstoqueRouteWithChildren = AdminEstoqueRoute._addFileChildren(
  AdminEstoqueRouteChildren,
)

interface AdminFinanceiroRouteChildren {
  AdminFinanceiroConfiguracoesRoute: typeof AdminFinanceiroConfiguracoesRoute
  AdminFinanceiroDreRoute: typeof AdminFinanceiroDreRoute
  AdminFinanceiroFluxoCaixaRoute: typeof AdminFinanceiroFluxoCaixaRoute
  AdminFinanceiroHistoricoRoute: typeof AdminFinanceiroHistoricoRoute
  AdminFinanceiroMovimentacoesRoute: typeof AdminFinanceiroMovimentacoesRoute
  AdminFinanceiroPagarRoute: typeof AdminFinanceiroPagarRoute
  AdminFinanceiroReceberRoute: typeof AdminFinanceiroReceberRoute
  AdminFinanceiroSessoesRoute: typeof AdminFinanceiroSessoesRoute
  AdminFinanceiroIndexRoute: typeof AdminFinanceiroIndexRoute
}

const AdminFinanceiroRouteChildren: AdminFinanceiroRouteChildren = {
  AdminFinanceiroConfiguracoesRoute: AdminFinanceiroConfiguracoesRoute,
  AdminFinanceiroDreRoute: AdminFinanceiroDreRoute,
  AdminFinanceiroFluxoCaixaRoute: AdminFinanceiroFluxoCaixaRoute,
  AdminFinanceiroHistoricoRoute: AdminFinanceiroHistoricoRoute,
  AdminFinanceiroMovimentacoesRoute: AdminFinanceiroMovimentacoesRoute,
  AdminFinanceiroPagarRoute: AdminFinanceiroPagarRoute,
  AdminFinanceiroReceberRoute: AdminFinanceiroReceberRoute,
  AdminFinanceiroSessoesRoute: AdminFinanceiroSessoesRoute,
  AdminFinanceiroIndexRoute: AdminFinanceiroIndexRoute,
}

const AdminFinanceiroRouteWithChildren = AdminFinanceiroRoute._addFileChildren(
  AdminFinanceiroRouteChildren,
)

interface AdminRouteChildren {
  AdminAmbientesImpressaoRoute: typeof AdminAmbientesImpressaoRoute
  AdminCategoriasRoute: typeof AdminCategoriasRoute
  AdminClientesRoute: typeof AdminClientesRoute
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRoute
  AdminCuponsRoute: typeof AdminCuponsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminEntregaRoute: typeof AdminEntregaRoute
  AdminEstoqueRoute: typeof AdminEstoqueRouteWithChildren
  AdminFinanceiroRoute: typeof AdminFinanceiroRouteWithChildren
  AdminImpressorasRoute: typeof AdminImpressorasRoute
  AdminPdvRoute: typeof AdminPdvRoute
  AdminPedidosRoute: typeof AdminPedidosRoute
  AdminProdutosRoute: typeof AdminProdutosRoute
  AdminRelatoriosRoute: typeof AdminRelatoriosRoute
  AdminRelatoriosDashboardRoute: typeof AdminRelatoriosDashboardRoute
  AdminRelatoriosPreviewRoute: typeof AdminRelatoriosPreviewRoute
  AdminSetoresRoute: typeof AdminSetoresRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAmbientesImpressaoRoute: AdminAmbientesImpressaoRoute,
  AdminCategoriasRoute: AdminCategoriasRoute,
  AdminClientesRoute: AdminClientesRoute,
  AdminConfiguracoesRoute: AdminConfiguracoesRoute,
  AdminCuponsRoute: AdminCuponsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminEntregaRoute: AdminEntregaRoute,
  AdminEstoqueRoute: AdminEstoqueRouteWithChildren,
  AdminFinanceiroRoute: AdminFinanceiroRouteWithChildren,
  AdminImpressorasRoute: AdminImpressorasRoute,
  AdminPdvRoute: AdminPdvRoute,
  AdminPedidosRoute: AdminPedidosRoute,
  AdminProdutosRoute: AdminProdutosRoute,
  AdminRelatoriosRoute: AdminRelatoriosRoute,
  AdminRelatoriosDashboardRoute: AdminRelatoriosDashboardRoute,
  AdminRelatoriosPreviewRoute: AdminRelatoriosPreviewRoute,
  AdminSetoresRoute: AdminSetoresRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface StoreRouteChildren {
  StoreAccountRoute: typeof StoreAccountRoute
  StoreCartRoute: typeof StoreCartRoute
  StoreCategoriesRoute: typeof StoreCategoriesRoute
  StoreCheckoutRoute: typeof StoreCheckoutRoute
  StorePaymentRoute: typeof StorePaymentRoute
  StoreSearchRoute: typeof StoreSearchRoute
  StoreIndexRoute: typeof StoreIndexRoute
  StoreOrderOrderIdRoute: typeof StoreOrderOrderIdRoute
  StoreProductProductIdRoute: typeof StoreProductProductIdRoute
}

const StoreRouteChildren: StoreRouteChildren = {
  StoreAccountRoute: StoreAccountRoute,
  StoreCartRoute: StoreCartRoute,
  StoreCategoriesRoute: StoreCategoriesRoute,
  StoreCheckoutRoute: StoreCheckoutRoute,
  StorePaymentRoute: StorePaymentRoute,
  StoreSearchRoute: StoreSearchRoute,
  StoreIndexRoute: StoreIndexRoute,
  StoreOrderOrderIdRoute: StoreOrderOrderIdRoute,
  StoreProductProductIdRoute: StoreProductProductIdRoute,
}

const StoreRouteWithChildren = StoreRoute._addFileChildren(StoreRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ConviteRoute: ConviteRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  StoreRoute: StoreRouteWithChildren,
  TermosDeUsoRoute: TermosDeUsoRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  LojaSlugOuIdRoute: LojaSlugOuIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
