/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as StoreRouteImport } from './routes/store'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StoreIndexRouteImport } from './routes/store/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as StoreSearchRouteImport } from './routes/store/search'
import { Route as StoreCheckoutRouteImport } from './routes/store/checkout'
import { Route as StoreCategoriesRouteImport } from './routes/store/categories'
import { Route as StoreCartRouteImport } from './routes/store/cart'
import { Route as StoreAccountRouteImport } from './routes/store/account'
import { Route as AdminStockRouteImport } from './routes/admin/stock'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminProductsRouteImport } from './routes/admin/products'
import { Route as AdminPdvRouteImport } from './routes/admin/pdv'
import { Route as AdminOrdersRouteImport } from './routes/admin/orders'
import { Route as AdminFinancialRouteImport } from './routes/admin/financial'
import { Route as AdminDeliveryRouteImport } from './routes/admin/delivery'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminCustomersRouteImport } from './routes/admin/customers'
import { Route as AdminCouponsRouteImport } from './routes/admin/coupons'
import { Route as AdminCategoriesRouteImport } from './routes/admin/categories'
import { Route as StoreProductProductIdRouteImport } from './routes/store/product.$productId'
import { Route as StoreOrderOrderIdRouteImport } from './routes/store/order.$orderId'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreIndexRoute = StoreIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StoreRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const StoreSearchRoute = StoreSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => StoreRoute,
} as any)
const StoreCheckoutRoute = StoreCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => StoreRoute,
} as any)
const StoreCategoriesRoute = StoreCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => StoreRoute,
} as any)
const StoreCartRoute = StoreCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => StoreRoute,
} as any)
const StoreAccountRoute = StoreAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => StoreRoute,
} as any)
const AdminStockRoute = AdminStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPdvRoute = AdminPdvRouteImport.update({
  id: '/pdv',
  path: '/pdv',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinancialRoute = AdminFinancialRouteImport.update({
  id: '/financial',
  path: '/financial',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDeliveryRoute = AdminDeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCouponsRoute = AdminCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const StoreProductProductIdRoute = StoreProductProductIdRouteImport.update({
  id: '/product/$productId',
  path: '/product/$productId',
  getParentRoute: () => StoreRoute,
} as any)
const StoreOrderOrderIdRoute = StoreOrderOrderIdRouteImport.update({
  id: '/order/$orderId',
  path: '/order/$orderId',
  getParentRoute: () => StoreRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/store': typeof StoreRouteWithChildren
  '/verify-email': typeof VerifyEmailRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/delivery': typeof AdminDeliveryRoute
  '/admin/financial': typeof AdminFinancialRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/pdv': typeof AdminPdvRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/stock': typeof AdminStockRoute
  '/store/account': typeof StoreAccountRoute
  '/store/cart': typeof StoreCartRoute
  '/store/categories': typeof StoreCategoriesRoute
  '/store/checkout': typeof StoreCheckoutRoute
  '/store/search': typeof StoreSearchRoute
  '/admin/': typeof AdminIndexRoute
  '/store/': typeof StoreIndexRoute
  '/store/order/$orderId': typeof StoreOrderOrderIdRoute
  '/store/product/$productId': typeof StoreProductProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/delivery': typeof AdminDeliveryRoute
  '/admin/financial': typeof AdminFinancialRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/pdv': typeof AdminPdvRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/stock': typeof AdminStockRoute
  '/store/account': typeof StoreAccountRoute
  '/store/cart': typeof StoreCartRoute
  '/store/categories': typeof StoreCategoriesRoute
  '/store/checkout': typeof StoreCheckoutRoute
  '/store/search': typeof StoreSearchRoute
  '/admin': typeof AdminIndexRoute
  '/store': typeof StoreIndexRoute
  '/store/order/$orderId': typeof StoreOrderOrderIdRoute
  '/store/product/$productId': typeof StoreProductProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/store': typeof StoreRouteWithChildren
  '/verify-email': typeof VerifyEmailRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/delivery': typeof AdminDeliveryRoute
  '/admin/financial': typeof AdminFinancialRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/pdv': typeof AdminPdvRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/stock': typeof AdminStockRoute
  '/store/account': typeof StoreAccountRoute
  '/store/cart': typeof StoreCartRoute
  '/store/categories': typeof StoreCategoriesRoute
  '/store/checkout': typeof StoreCheckoutRoute
  '/store/search': typeof StoreSearchRoute
  '/admin/': typeof AdminIndexRoute
  '/store/': typeof StoreIndexRoute
  '/store/order/$orderId': typeof StoreOrderOrderIdRoute
  '/store/product/$productId': typeof StoreProductProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/store'
    | '/verify-email'
    | '/admin/categories'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/delivery'
    | '/admin/financial'
    | '/admin/orders'
    | '/admin/pdv'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/stock'
    | '/store/account'
    | '/store/cart'
    | '/store/categories'
    | '/store/checkout'
    | '/store/search'
    | '/admin/'
    | '/store/'
    | '/store/order/$orderId'
    | '/store/product/$productId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/admin/categories'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/delivery'
    | '/admin/financial'
    | '/admin/orders'
    | '/admin/pdv'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/stock'
    | '/store/account'
    | '/store/cart'
    | '/store/categories'
    | '/store/checkout'
    | '/store/search'
    | '/admin'
    | '/store'
    | '/store/order/$orderId'
    | '/store/product/$productId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/store'
    | '/verify-email'
    | '/admin/categories'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/delivery'
    | '/admin/financial'
    | '/admin/orders'
    | '/admin/pdv'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/stock'
    | '/store/account'
    | '/store/cart'
    | '/store/categories'
    | '/store/checkout'
    | '/store/search'
    | '/admin/'
    | '/store/'
    | '/store/order/$orderId'
    | '/store/product/$productId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  StoreRoute: typeof StoreRouteWithChildren
  VerifyEmailRoute: typeof VerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/': {
      id: '/store/'
      path: '/'
      fullPath: '/store/'
      preLoaderRoute: typeof StoreIndexRouteImport
      parentRoute: typeof StoreRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/store/search': {
      id: '/store/search'
      path: '/search'
      fullPath: '/store/search'
      preLoaderRoute: typeof StoreSearchRouteImport
      parentRoute: typeof StoreRoute
    }
    '/store/checkout': {
      id: '/store/checkout'
      path: '/checkout'
      fullPath: '/store/checkout'
      preLoaderRoute: typeof StoreCheckoutRouteImport
      parentRoute: typeof StoreRoute
    }
    '/store/categories': {
      id: '/store/categories'
      path: '/categories'
      fullPath: '/store/categories'
      preLoaderRoute: typeof StoreCategoriesRouteImport
      parentRoute: typeof StoreRoute
    }
    '/store/cart': {
      id: '/store/cart'
      path: '/cart'
      fullPath: '/store/cart'
      preLoaderRoute: typeof StoreCartRouteImport
      parentRoute: typeof StoreRoute
    }
    '/store/account': {
      id: '/store/account'
      path: '/account'
      fullPath: '/store/account'
      preLoaderRoute: typeof StoreAccountRouteImport
      parentRoute: typeof StoreRoute
    }
    '/admin/stock': {
      id: '/admin/stock'
      path: '/stock'
      fullPath: '/admin/stock'
      preLoaderRoute: typeof AdminStockRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pdv': {
      id: '/admin/pdv'
      path: '/pdv'
      fullPath: '/admin/pdv'
      preLoaderRoute: typeof AdminPdvRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/financial': {
      id: '/admin/financial'
      path: '/financial'
      fullPath: '/admin/financial'
      preLoaderRoute: typeof AdminFinancialRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/delivery': {
      id: '/admin/delivery'
      path: '/delivery'
      fullPath: '/admin/delivery'
      preLoaderRoute: typeof AdminDeliveryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/coupons': {
      id: '/admin/coupons'
      path: '/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AdminCouponsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/store/product/$productId': {
      id: '/store/product/$productId'
      path: '/product/$productId'
      fullPath: '/store/product/$productId'
      preLoaderRoute: typeof StoreProductProductIdRouteImport
      parentRoute: typeof StoreRoute
    }
    '/store/order/$orderId': {
      id: '/store/order/$orderId'
      path: '/order/$orderId'
      fullPath: '/store/order/$orderId'
      preLoaderRoute: typeof StoreOrderOrderIdRouteImport
      parentRoute: typeof StoreRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminCouponsRoute: typeof AdminCouponsRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminDeliveryRoute: typeof AdminDeliveryRoute
  AdminFinancialRoute: typeof AdminFinancialRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPdvRoute: typeof AdminPdvRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStockRoute: typeof AdminStockRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminCouponsRoute: AdminCouponsRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminDeliveryRoute: AdminDeliveryRoute,
  AdminFinancialRoute: AdminFinancialRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPdvRoute: AdminPdvRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStockRoute: AdminStockRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface StoreRouteChildren {
  StoreAccountRoute: typeof StoreAccountRoute
  StoreCartRoute: typeof StoreCartRoute
  StoreCategoriesRoute: typeof StoreCategoriesRoute
  StoreCheckoutRoute: typeof StoreCheckoutRoute
  StoreSearchRoute: typeof StoreSearchRoute
  StoreIndexRoute: typeof StoreIndexRoute
  StoreOrderOrderIdRoute: typeof StoreOrderOrderIdRoute
  StoreProductProductIdRoute: typeof StoreProductProductIdRoute
}

const StoreRouteChildren: StoreRouteChildren = {
  StoreAccountRoute: StoreAccountRoute,
  StoreCartRoute: StoreCartRoute,
  StoreCategoriesRoute: StoreCategoriesRoute,
  StoreCheckoutRoute: StoreCheckoutRoute,
  StoreSearchRoute: StoreSearchRoute,
  StoreIndexRoute: StoreIndexRoute,
  StoreOrderOrderIdRoute: StoreOrderOrderIdRoute,
  StoreProductProductIdRoute: StoreProductProductIdRoute,
}

const StoreRouteWithChildren = StoreRoute._addFileChildren(StoreRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  StoreRoute: StoreRouteWithChildren,
  VerifyEmailRoute: VerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
